version: '3.1'

services:
  api:
    build:
      context: .
    container_name: fastapi-application
    expose:
      - 8000
    depends_on:
      - mongodb
      - redis

  redis:
    image: redis:latest
    expose:
      - 6379

  mongodb:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    expose:
      - 27017

  nginx:
    image: nginx
    volumes:
      - ./configs/nginx:/etc/nginx/sites-available/default
    ports:
      - '80:80'
