version: '3.1'

# TODO add mount log dir from all containers

services:

  redis:
    container_name: redis
    image: redis:latest
    expose:
      - 6379

  mongodb:
    container_name: mongo
    image: mongo:6
    restart: always
    volumes:
      - ./data:/data/db
    expose:
      - 27017

  api:
    build:
      context: .
    image: app_image:latest
    container_name: application
    expose:
      - 8000
    depends_on:
      - mongodb
      - redis

  celery:
    image: app_image:latest
    container_name: celery
    entrypoint: celery
    command: -A app.celery_twitter worker -B -Q --log-level=WARNING
    depends_on:
      - api
      - mongodb
      - redis

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - api

